export type PageId =
  | 'dashboard'
  | 'inventory'
  | 'asset_structure'
  | 'calendar'
  | 'tasks'
  | 'calibration'
  | 'failures'
  | 'purchase_requests'
  | 'smart_cart'
  | 'vendors'
  | 'reports'
  | 'users'
  | 'my_workgroup'
  | 'settings';

export type PermissionLevel = 'none' | 'view' | 'action';

export interface CategoryApprovalStep {
  roleCode: string;
  roleTitleFa: string;
}

export type AssetFieldType = 'text' | 'number' | 'select' | 'boolean' | 'date' | 'file' | 'image';

export interface AssetRequirementField {
  id: string;
  name: string;
  type: AssetFieldType;
  required: boolean;
  helpText?: string;
  options?: string[];
  order: number;
  assignedRole?: string; // e.g. 'warehouse_keeper' | 'procurement_officer' | 'biomedical_engineer' | 'finance_manager' | 'dept_head'
  assignedRoleTitleFa?: string; // e.g. 'انباردار' | 'مسئول خرید' | 'مهندس پزشکی' | 'مدیر مالی' | 'سرپرست بخش'
}

export interface AssetClassification {
  id: string;
  name: string;
  slug: string;
  description: string;
  parentId?: string;
  parentName?: string;
  itemsCount: number;
  isActive: boolean;
  isCustom?: boolean; // آیا این ساختار سفارشی بیمارستان است یا پیش‌فرض مرجع
  domain?: 'medical' | 'laboratory' | 'hospital' | 'dental' | 'consumables' | 'general_hospital' | 'it' | 'facilities' | 'administrative' | 'custom'; // قلمرو ساختار
  code?: string; // کد رده‌بندی یا استاندارد مرجع
  path?: string; // مسیر کامل سلسله‌مراتبی
  icon?: string;
  isLeaf?: boolean; // آیا این رده، ساختار نهایی جهت ثبت موجودی است
  createdAt: string;
  updatedAt: string;
  fields: AssetRequirementField[];
  defaultFieldsBackup?: AssetRequirementField[]; // پشتیبان فیلدهای استاندارد جهت امکان بازنشانی
  approvalChain?: CategoryApprovalStep[];
}

export type EquipmentStatus =
  | 'active' // فعال و آماده به کار
  | 'in_use' // در حال استفاده
  | 'under_maintenance' // در حال تعمیر
  | 'calibrating' // در حال کالیبراسیون
  | 'idle' // بلااستفاده / آماده واگذاری
  | 'decommissioned' // اسقاط شده / خارج از رده
  | 'in_stock' // موجود در انبار
  | 'low_stock' // کمبود موجودی
  | 'out_of_stock' // ناموجود / تمام شده
  | 'expired' // منقضی شده
  | 'near_expiry' // در شرف انقضا
  | 'draft'; // پیش‌نویس

export type ItemKind = 'device' | 'consumable';

export interface EquipmentComment {
  id: string;
  authorName: string;
  authorRole: string;
  department?: string;
  date: string;
  commentType: 'operational_note' | 'usability' | 'shift_handover' | 'general';
  rating?: number; // 1 to 5
  text: string;
}

export interface EquipmentItem {
  id: string;
  code: string; // e.g. EQ-1042
  faName: string;
  enName: string;
  category: string; // Level 1 (Category)
  subcategory?: string; // Level 2 (Subcategory)
  type?: string; // Level 3 (Type)
  classificationPath?: string; // Full Breadcrumb: Category > Subcategory > Type
  brand: string;
  model: string;
  department: string;
  location: string;
  status: EquipmentStatus;
  itemKind?: ItemKind;
  purchaseDate: string;
  price: number; // Toman
  serialNumber: string;
  warrantyExpiry: string;
  nextCalibrationDate: string;
  safetyScore: number; // 0 - 100
  owner: string;
  specs?: Record<string, string>;
  documents?: { title: string; url: string; date: string }[];
  comments?: EquipmentComment[];
  isDraft?: boolean;
  quantity?: number;
  unit?: string;
  batchNo?: string;
  expiryDate?: string;
  supplier?: string;
  creator?: string;
  createdAt?: string;
  missingFields?: string[];
  groupKey?: string;
}

export interface TaskEvent {
  id: string;
  title: string;
  type:
    | 'calibration'
    | 'expiry'
    | 'inspection'
    | 'purchase'
    | 'maintenance'
    | 'inventory_audit'
    | 'tagging'
    | 'stock_check'
    | 'asset_transfer'
    | 'draft_completion';
  priority: 'high' | 'medium' | 'low';
  assignedTo: string;
  role: string;
  dueDate: string;
  status: 'open' | 'in_progress' | 'completed';
  autoGenerated: boolean;
  equipmentCode?: string;
  equipmentName?: string;
  targetDraftId?: string;
  notes?: string;
}

export interface CustomEquipmentFilterCriteria {
  departments?: string[];
  statuses?: EquipmentStatus[];
  categories?: string[];
  brands?: string[];
  itemKind?: ItemKind | 'all';
  hasWarrantyOnly?: boolean;
  requiresCalibration?: boolean;
  minSafetyScore?: number;
  maxSafetyScore?: number;
  searchKeyword?: string;
}

export interface CustomEquipmentFilter {
  id: string;
  name: string;
  description?: string;
  color?: 'sky' | 'emerald' | 'purple' | 'amber' | 'rose' | 'indigo' | 'slate';
  icon?: string;
  criteria: CustomEquipmentFilterCriteria;
  createdBy: string;
  creatorRole?: string;
  createdAt: string;
  updatedAt?: string;
  isActive: boolean;
}

export interface CalibrationRecord {
  id: string;
  equipmentId: string;
  equipmentCode: string;
  equipmentName: string;
  certNumber: string;
  issueDate: string;
  expiryDate: string;
  status: 'valid' | 'expiring_soon' | 'expired';
  inspector: string;
  agency: string;
  safetyNotes: string;
  operatorFeedback: string;
  documentUrl?: string;
}

export interface FailureReport {
  id: string;
  reportNo: string;
  equipmentCode: string;
  equipmentName: string;
  department: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  reporterName: string;
  reporterRole: string;
  reportDate: string;
  defectDescription: string;
  status: 'reported' | 'assigned' | 'in_repair' | 'resolved';
  technicianAssigned?: string;
  actionsTaken?: string;
  resolvedDate?: string;
}

export interface RequestItem {
  name: string;
  quantity: number;
  unit: string;
  estimatedPrice: number;
}

export interface PurchaseRequest {
  id: string;
  requestNo: string;
  department: string;
  requesterName: string;
  requesterRole: string;
  requesterRoleKey?: UserRole; // 'asset_manager' vs operational roles ('nurse_operator', 'dept_head', 'biomedical_engineer', etc.)
  urgency: 'critical' | 'high' | 'normal';
  date: string;
  reason: string;
  items: RequestItem[];
  totalEstimate: number;
  status:
    | 'pending_asset_manager'
    | 'pending_finance'
    | 'pending_procurement'
    | 'approved'
    | 'rejected'
    | 'purchased'
    | 'pending_dept_head'
    | 'pending_equipment_manager';
  approvalStage: number; // 1: created, 2: asset_manager / finance, 3: finance / procurement, 4: cart / approved
  totalStages?: number; // 3 for asset_manager initiated, 4 for operational user initiated
  comments: { user: string; role: string; text: string; date: string; action: string }[];
}

export interface SmartCartItem {
  id: string;
  equipmentName: string;
  category: string;
  brand: string;
  vendorName: string;
  vendorId: string;
  quantity: number;
  unitPrice: number;
  shippingCost: number;
  discountPercentage: number;
  recommendationReason: string;
  urgencyLevel: 'high' | 'medium' | 'low';
  strategyTag: 'optimized' | 'discount' | 'urgent' | 'low_shipping';
}

export type CartStrategy = 'optimized' | 'discount' | 'urgent' | 'low_shipping';

export interface ClosedCartBatch {
  id: string;
  batchCode: string;
  strategy: CartStrategy;
  strategyTitle: string;
  createdAt: string;
  closedBy: string;
  closedByRole: string;
  totalGross: number;
  totalDiscount: number;
  totalShipping: number;
  netTotal: number;
  itemsCount: number;
  items: SmartCartItem[];
  financialStatus: 'pending_review' | 'approved' | 'rejected' | 'partially_approved';
  financeReviewer?: string;
  financeReviewDate?: string;
  financeNote?: string;
  itemDecisions?: Record<string, { approved: boolean; note?: string }>;
}

export interface Vendor {
  id: string;
  code: string;
  name: string;
  brandRepresentative?: string;
  categories: string[];
  specialty: string;
  contactPerson: string;
  contactRole?: string;
  phone: string;
  mobile?: string;
  email: string;
  address?: string;
  city: string;
  ircLicenseNumber: string;
  ircStatus: 'valid' | 'renewal_pending' | 'expired';
  slaScore: number; // 0-100%
  slaComplianceRate: number; // 0-100%
  responseTimeHours: number; // ساعت پاسخگویی اورژانسی
  warrantySupportMonths: number; // ماه گارانتی
  contractStatus: 'active' | 'expiring_soon' | 'inactive';
  contractExpiry: string; // تاریخ سررسید قرارداد
  activeContractsCount: number;
  rating: number; // 1-5
  priceScore: number; // 1-10
  qualityScore: number; // 1-10
  status: 'active' | 'under_review' | 'inactive';
}

export type UserRole =
  | 'hospital_admin'
  | 'support_tech'
  | 'procurement_officer'
  | 'biomedical_engineer'
  | 'dept_head'
  | 'asset_manager'
  | 'nurse_operator'
  | 'warehouse_keeper'
  | 'finance_manager'
  | string;

export interface SupervisorResponsibilities {
  manageSubPermissions: boolean;
  supervisePerformance: boolean;
  viewActivityStatus: boolean;
  receiveSubNotifications: boolean;
}

export interface RoleDefinition {
  id: string;
  code: UserRole;
  titleFa: string;
  description: string;
  supervisorRoleId?: string;
  supervisorUserId?: string;
  supervisorName?: string;
  supervisorResponsibilities?: SupervisorResponsibilities;
  permissions: string[];
  modulePermissions?: Record<string, PermissionLevel>;
  isCustom?: boolean;
}

export interface EmployeeFeedback {
  id: string;
  authorName: string;
  authorRole: string;
  text: string;
  date: string;
}

export interface AppUser {
  id: string;
  personnelCode: string;
  username: string;
  password?: string;
  name: string;
  avatarUrl?: string;
  role: UserRole;
  roleFa: string;
  email: string;
  phone: string;
  department: string;
  status: 'active' | 'inactive';
  lastLogin: string;
  permissions: string[];
  modulePermissions?: Record<string, PermissionLevel>;
  individualOverrides?: Record<string, boolean>; // legacy compatibility
  pagePermissions?: Record<string, { view: boolean; action: boolean }>;
  supervisorId?: string;
  supervisorName?: string;
  supervisorRoleTitle?: string;
  supervisorLevel?: 1 | 2 | 3;
  allowedPages?: PageId[];
  description?: string;
  performanceScore?: number; // 0 - 100
  feedbacks?: EmployeeFeedback[];
  workgroupTasksCount?: number;
  delayedTasksCount?: number;
}

export interface SystemNotification {
  id: string;
  title: string;
  desc: string;
  time: string;
  type: 'warning' | 'success' | 'danger' | 'info' | 'draft_alert';
  draftId?: string;
  equipmentCode?: string;
  equipmentName?: string;
  createdByUser?: string;
  requiredAction?: string;
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  timestamp: string;
  suggestedActions?: { label: string; page?: PageId; actionKey?: string }[];
}
